/* Q1. Total revenue generated by male vs. female customers */
SELECT Gender, SUM(`Purchase Amount (USD)`) AS revenue
FROM data_analytics.customer_shopping_behavior
GROUP BY Gender;

/* Q2. High-spending Discount Users */
-- Using * to bypass the 'ï»¿Customer ID' naming issue
SELECT *
FROM data_analytics.customer_shopping_behavior 
WHERE `Discount Applied` = 'Yes' 
AND `Purchase Amount (USD)` >= (SELECT AVG(`Purchase Amount (USD)`) FROM data_analytics.customer_shopping_behavior)
LIMIT 1000;

/* Q3. Top 5 products with the highest average review rating */
SELECT `Item Purchased`, ROUND(AVG(`Review Rating`), 2) AS "Average Product Rating"
FROM data_analytics.customer_shopping_behavior
GROUP BY `Item Purchased`
ORDER BY AVG(`Review Rating`) DESC
LIMIT 5;

/* Q4. Average Purchase Amounts: Standard vs. Express Shipping */
SELECT `Shipping Type`, ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_purchase
FROM data_analytics.customer_shopping_behavior
WHERE `Shipping Type` IN ('Standard', 'Express')
GROUP BY `Shipping Type`;

/* Q5. Subscription status performance metrics */
SELECT `Subscription Status`,
       COUNT(*) AS total_customers,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_spend,
       ROUND(SUM(`Purchase Amount (USD)`), 2) AS total_revenue
FROM data_analytics.customer_shopping_behavior
GROUP BY `Subscription Status`
ORDER BY total_revenue DESC, avg_spend DESC;

/* Q6. Top 5 products by discount adoption rate */
SELECT `Item Purchased`,
       ROUND(100.0 * SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM data_analytics.customer_shopping_behavior
GROUP BY `Item Purchased`
ORDER BY discount_rate DESC
LIMIT 5;

/* Q7. Customer Segmentation by Loyalty */
WITH customer_type AS (
    SELECT `Previous Purchases`,
    CASE 
        WHEN `Previous Purchases` <= 1 THEN 'New'
        WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
    FROM data_analytics.customer_shopping_behavior
)
SELECT customer_segment, COUNT(*) AS "Number of Customers" 
FROM customer_type 
GROUP BY customer_segment;

/* Q8. Top 3 most purchased products per category */

WITH item_counts AS (
    SELECT Category,
           `Item Purchased`,
           COUNT(*) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY Category ORDER BY COUNT(*) DESC) AS item_rank
    FROM data_analytics.customer_shopping_behavior
    GROUP BY Category, `Item Purchased`
)
SELECT item_rank, Category, `Item Purchased`, total_orders
FROM item_counts
WHERE item_rank <= 3;

/* Q9. Subscription likelihood for repeat buyers (>5 purchases) */
SELECT `Subscription Status`,
       COUNT(*) AS repeat_buyers
FROM data_analytics.customer_shopping_behavior
WHERE `Previous Purchases` > 5
GROUP BY `Subscription Status`;

/* Q10. Revenue contribution by Age Group */
SELECT 
    CASE 
        WHEN Age < 30 THEN '18-29'
        WHEN Age BETWEEN 30 AND 50 THEN '30-50'
        ELSE '51+' 
    END AS age_group,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM data_analytics.customer_shopping_behavior
GROUP BY 1 
ORDER BY total_revenue DESC;
